server:
  port: 8083

---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jobnwnyo_db
    username: root
    password: Dream@1914
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true